### ISSUE TITLE
Clickhouse-only configuration has been developed and benchmarked

### ISSUE THREAD

**Issue by sheridancbio** [cBioPortal/rfc80-team#2]
- [ ] local / kubernetes clickhouse installation running via Docker image
- [ ] cBioPortal branch showing 2024_02 hackathon effort for a pure clickhouse persistence has been understood
- [ ] remaining SQL dialect clashes and incompatibilities (case sensitivities) have been identified, planned, resolved
- [ ] clickhouse-only persistence implementation has been benchmarked per RFC-80 benchmarking measures

Deliverable : report on success or shortfalls (required work) for clickhouse only operation (with recommendation)
